# Generated by Django 4.2.7 on 2026-02-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0003_alter_menuitem_options_remove_menuitem_order_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FeaturedDish',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0, help_text='Display order on the home page')),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('menu_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='featured_as', to='menu.menuitem')),
            ],
            options={
                'verbose_name': 'Saralangan Taom',
                'verbose_name_plural': 'Saralangan Taomlar',
                'ordering': ['order', 'menu_item__name'],
            },
        ),
    ]
