# Generated by Django 4.2.7 on 2026-02-11 16:04

from django.db import migrations, models
import imagekit.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('menu', '0004_featureddish'),
    ]

    operations = [
        migrations.AlterField(
            model_name='category',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='categories/'),
        ),
        migrations.AlterField(
            model_name='menuitem',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='menu_items/'),
        ),
        migrations.AlterField(
            model_name='promotion',
            name='image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text="Aksiya rasmi (bo'lmasa, mahsulot rasmi ishlatiladi)", null=True, upload_to='promotions/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='about_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='restaurant/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_image',
            field=imagekit.models.fields.ProcessedImageField(blank=True, null=True, upload_to='restaurant/'),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_subtitle',
            field=models.CharField(default="O'zbekistondagi eng mazali pizza va grill taomlarini tatib ko'ring", max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_subtitle_ru',
            field=models.CharField(default='Попробуйте самую вкусную пиццу и гриль-блюда в Узбекистане', max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_subtitle_uz',
            field=models.CharField(default="O'zbekistondagi eng mazali pizza va grill taomlarini tatib ko'ring", max_length=500),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='hero_title',
            field=models.CharField(default='Pizza Centr Garden', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_name',
            field=models.CharField(default='Pizza Centr Garden', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_name_ru',
            field=models.CharField(default='Пицца Центр Гарден', max_length=200),
        ),
        migrations.AlterField(
            model_name='restaurantinfo',
            name='restaurant_name_uz',
            field=models.CharField(default='Pizza Centr Garden', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='email',
            field=models.EmailField(default='info@pizzacentr.uz', max_length=254),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='logo',
            field=imagekit.models.fields.ProcessedImageField(blank=True, help_text='Site logo image', null=True, upload_to='site/'),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name',
            field=models.CharField(default='Pizza Centr Garden', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_ru',
            field=models.CharField(default='Пицца Центр Гарден', max_length=200),
        ),
        migrations.AlterField(
            model_name='sitesettings',
            name='site_name_uz',
            field=models.CharField(default='Pizza Centr Garden', max_length=200),
        ),
    ]
